### ISSUE TITLE
[bug: i18n] Serbian translation of VISION file doesn't specify script

### ISSUE THREAD

**Issue by DerekNonGeneric** [OpenINF/.github#84]
> Serbian is practically the only European standard language whose speakers are fully functionally digraphic, using both Cyrillic and Latin alphabets.
> &mdash; https://en.wikipedia.org/wiki/Serbian_language#cite_ref-18

This seems to be a unique case in natural languages, but the Serbian language can be expressed in either Latin ([`sr_Latn`](https://www.localeplanet.com/icu/sr_Latn/index.html)) or Cyrillic script ([`sr_Cyrl`](https://www.localeplanet.com/icu/sr_Cyrl/index.html)), so what i said about &ldquo;two-letter codes, one per language&rdquo; in https://github.com/openinf/.github/pull/34#issuecomment-1230322175 is a little bit incorrect due to this edge case. I think we will need to specify which one of the alphabets we are using when making these translations to prevent mixing them.

/cc @emmitrovic as i am unsure which one we should use (is one preferable or maybe we need both?)

I am not exactly sure, but the only other time this may come up elsewhere is when distinguishing btwx Simplified Chinese ([`zh_Hans`](https://www.localeplanet.com/icu/zh_Hans/index.html)) and Traditional Chinese ([`zh_Hant`](https://www.localeplanet.com/icu/zh_Hant/index.html))&hellip;

/cc @septs as this file naming scheme seems to be gaining widespread adoption (guideline may be needed)

To be clear, this is not about localization in the sense of wanting to distinguish btwx Portuguese from Portugal ([`pt_PT`](https://www.localeplanet.com/icu/pt_PT/index.html)) and Portuguese from Brazil ([`pt_BR`](https://www.localeplanet.com/icu/pt_BR/index.html)), which use the same alphabets. On the topic of Portuguese: I was hoping to be able to _only_ use `pt` and leave the translation style up to whomever does the translation. For example, some things sound better in `pt_BR` and others in `pt_PT`, so if we can avoid making the distinction, i would prefer that.

/cc @erickwendel as am unsure if this would be practical (am still learning and unsure of edge cases)

Any additional insight you all can provide would be appreciated!

[^1]: https://en.wikipedia.org/wiki/Serbian_language#cite_ref-18

**Comment by emmitrovic** [comment]
We'll use (sr_Latn) for this! 👍🏻

**Comment by DerekNonGeneric** [comment]
Relevant to this discussion: how a language selector component could work for this is discussed at https://github.com/unicode-org/icu4x/issues/2686.
